-- AlterTable
ALTER TABLE `Noticia` MODIFY `categoria` ENUM('SAUDE', 'EDUCACAO', 'INFRAESTRUTURA', 'CULTURA', 'ESPORTE', 'ADMINISTRAÇÃO PÚBLICA', 'DESENVOLVIMENTO ECONÔMICO', 'SERVICOS', 'OBRAS', 'TRANSPORTE', 'ASSISTÊNCIA SOCIAL', 'SEGURANCA', 'HABITACAO', 'ECONOMIA', 'EMPREGOS', 'LICITACOES', 'EVENTOS', 'TURISMO', 'MEIO AMBIENTE') NOT NULL;
