/*
  Warnings:

  - The values [ADMINISTRAÇAO PUBLICA,DESENVOLVIMENTO ECONOMICO,ASSISTENCIA SOCIAL,MEIO AMBIENTE] on the enum `Noticia_categoria` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `Noticia` MODIFY `categoria` ENUM('SAUDE', 'EDUCACAO', 'INFRAESTRUTURA', 'CULTURA', 'ESPORTE', 'ADMINISTRACAO_PUBLICA', 'DESENVOLVIMENTO_ECONOMICO', 'SERVICOS', 'OBRAS', 'TRANSPORTE', 'ASSISTENCIA_SOCIAL', 'SEGURANCA', 'HABITACAO', 'ECONOMIA', 'EMPREGOS', 'LICITACOES', 'EVENTOS', 'TURISMO', 'MEIO_AMBIENTE') NOT NULL;
